spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - profile
              - email
          naver:
            client-id:
            client-secret: 
            client-name: Naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springex
    username: springex
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.MariaDB106Dialect

    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
